conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
remote_ci_setup:
  - conda-forge-ci-setup=4
  # https://github.com/conda/conda-build/issues/5613
  - conda-build <24.9
test: native_and_emulated
